/*

 BIGX.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : D:\BaiduNetdiskDownload\map\map.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bigXWidth 4
#define bigXHeight 4
#define bigXBank 0

unsigned char bigX[] =
{
  0x35,0x37,0x37,0x36,0x37,0x35,0x36,0x37,0x37,0x36,
  0x35,0x37,0x36,0x37,0x37,0x35
};

/* End of BIGX.C */
